-- REPORTE GENERAL
SELECT 
    'Equipos Totales' AS Descripcion, 
    (SELECT COUNT(*) FROM EQUIPO) AS Cantidad 
UNION
SELECT 
    'Equipos Habilitados' AS Descripcion, 
    (SELECT COUNT(*) FROM EQUIPO WHERE ESTADO = 'HABILITADO') AS Cantidad 
UNION
SELECT 
    'Equipos Inhabilitados' AS Descripcion, 
    (SELECT COUNT(*) FROM EQUIPO WHERE ESTADO = 'INHABILITADO') AS Cantidad 
UNION
SELECT 
    'SIMs Totales' AS Descripcion, 
    (SELECT COUNT(*) FROM SIM) AS Cantidad 
UNION
SELECT 
    'SIMs Habilitadas' AS Descripcion, 
    (SELECT COUNT(*) FROM SIM WHERE ESTADO = 'HABILITADO') AS Cantidad 
UNION
SELECT 
    'SIMs Inhabilitadas' AS Descripcion, 
    (SELECT COUNT(*) FROM SIM WHERE ESTADO = 'INHABILITADO') AS Cantidad 
UNION
SELECT 
    'Bajas de Equipo' AS Descripcion, 
    (SELECT COUNT(*) FROM BAJAS_EQUIPOS) AS Cantidad 
UNION
SELECT 
    'Migraciones de SIM' AS Descripcion, 
    (SELECT COUNT(*) FROM MIGRACION_SIM) AS Cantidad 
UNION
SELECT 
    'Asignaciones SIM' AS Descripcion, 
    (SELECT COUNT(*) FROM ASIGNACION_SIM) AS Cantidad 
UNION
SELECT 
    'Asignaciones Equipo' AS Descripcion, 
    (SELECT COUNT(*) FROM ASIGNACION_EQUIPO) AS Cantidad 
UNION
SELECT 
    'Asignaciones Activo' AS Descripcion, 
    (SELECT COUNT(*) FROM ASIGNACION_ACTIVO) AS Cantidad
UNION
SELECT 
    'Activos Activados' AS Descripcion, 
    (SELECT COUNT(*) FROM ACTIVO WHERE ESTADO = 'ACTIVADO') AS Cantidad 
UNION
SELECT 
    'Activos Habilitados' AS Descripcion, 
    (SELECT COUNT(*) FROM ACTIVO WHERE ESTADO = 'HABILITADO') AS Cantidad 
UNION
SELECT 
    'Activos Inhabilitados' AS Descripcion, 
    (SELECT COUNT(*) FROM ACTIVO WHERE ESTADO = 'INHABILITADO') AS Cantidad 
UNION
SELECT 
    'Activos en Venta' AS Descripcion, 
    (SELECT COUNT(*) FROM ASIGNACION_EQUIPO WHERE ESTADO = 'VENTA') AS Cantidad 
UNION
SELECT 
    'Activos en Renta' AS Descripcion, 
    (SELECT COUNT(*) FROM ASIGNACION_EQUIPO WHERE ESTADO = 'RENTA') AS Cantidad
UNION
SELECT 
    'Position Logic' AS Descripcion, 
    (SELECT COUNT(*) FROM ASIGNACION_PLATAFORMA WHERE PLATAFORMA_PLAT_ID = (SELECT PLAT_ID FROM PLATAFORMA WHERE NOMBRE = 'POSITION LOGIC')) AS Cantidad
UNION
SELECT 
    'Red GPS' AS Descripcion, 
    (SELECT COUNT(*)  FROM ASIGNACION_PLATAFORMA WHERE PLATAFORMA_PLAT_ID = (SELECT PLAT_ID FROM PLATAFORMA WHERE NOMBRE = 'RED GPS')) AS Cantidad;


-- REPORTE GENERAL POR INTERVALO DE FECHAS
SELECT
    'Equipos asignados a activos' AS Descripcion,
    COUNT(DISTINCT AE.EQUIPO_EQUI_ID) AS Cantidad
    FROM ASIGNACION_EQUIPO AE
    LEFT JOIN EQUIPO E ON AE.EQUIPO_EQUI_ID = E.EQUI_ID
    WHERE AE.FECHA_ASIGNACION_EQUIPO BETWEEN '2023-11-01' AND '2023-11-30'
    AND E.ESTADO = 'ACTIVADO'
UNION
SELECT
    'Equipos no asignados a activos' AS Descripcion,
    COUNT(DISTINCT E.EQUI_ID) AS Cantidad
    FROM ASIGNACION_SIM ASIM
    LEFT JOIN EQUIPO E ON ASIM.EQUIPO_EQUI_ID = E.EQUI_ID
    WHERE ASIM.FECHA_ASIGNACION_SIM BETWEEN '2023-11-01' AND '2023-11-30'
    AND E.ESTADO = 'HABILITADO'
UNION
SELECT
    'Sim asignadas a equipos' AS Descripcion,
    COUNT(DISTINCT ASIM.SIM_SIM_ID) AS Cantidad
    FROM ASIGNACION_SIM ASIM
    LEFT JOIN SIM S ON ASIM.SIM_SIM_ID = S.SIM_ID
    WHERE ASIM.FECHA_ASIGNACION_SIM BETWEEN '2023-11-01' AND '2023-11-30'
    AND S.ESTADO = 'HABILITADO'
UNION
SELECT
    'Activos asignados a clientes' AS Descripcion,
    COUNT(DISTINCT AA.ACTIVO_ACT_ID) AS Cantidad
    FROM ASIGNACION_ACTIVO AA
    LEFT JOIN ACTIVO A ON AA.ACTIVO_ACT_ID = A.ACT_ID
    WHERE AA.FECHA BETWEEN '2023-11-01' AND '2023-11-30'
    AND A.ESTADO = 'ACTIVADO'
UNION
SELECT
    'Activos no asignados a clientes' AS Descripcion,
    COUNT(DISTINCT AE.ACTIVO_ACT_ID) AS Cantidad
    FROM ASIGNACION_EQUIPO AE
    LEFT JOIN ACTIVO A ON AE.ACTIVO_ACT_ID = A.ACT_ID
    WHERE AE.FECHA_ASIGNACION_EQUIPO BETWEEN '2023-11-01' AND '2023-11-30'
    AND A.ESTADO = 'HABILITADO'
UNION
SELECT
    'Activos en venta' AS Descripcion,
    COUNT(DISTINCT AE.ACTIVO_ACT_ID) AS Cantidad
    FROM ASIGNACION_EQUIPO AE
    LEFT JOIN EQUIPO E ON AE.EQUIPO_EQUI_ID = E.EQUI_ID
    WHERE AE.FECHA_ASIGNACION_EQUIPO BETWEEN '2023-11-01' AND '2023-11-30'
    AND AE.ESTADO = 'VENTA'
UNION
SELECT
    'Activos en renta' AS Descripcion,
    COUNT(DISTINCT AE.ACTIVO_ACT_ID) AS Cantidad
    FROM ASIGNACION_EQUIPO AE
    LEFT JOIN EQUIPO E ON AE.EQUIPO_EQUI_ID = E.EQUI_ID
    WHERE AE.FECHA_ASIGNACION_EQUIPO BETWEEN '2023-11-01' AND '2023-11-30'
    AND AE.ESTADO = 'RENTA'
UNION
SELECT
    'Activos con POSITION LOGIC' AS Descripcion,
    COUNT(DISTINCT AP.ACTIVO_ACT_ID) AS Cantidad
    FROM ASIGNACION_PLATAFORMA AP
    LEFT JOIN PLATAFORMA P ON AP.PLATAFORMA_PLAT_ID = P.PLAT_ID
    WHERE AP.FECHA_ASIGNACION BETWEEN '2023-11-01' AND '2023-11-30'
    AND P.NOMBRE = 'POSITION LOGIC'
UNION
SELECT
    'Activos con RED GPS' AS Descripcion,
    COUNT(DISTINCT AP.ACTIVO_ACT_ID) AS Cantidad
    FROM ASIGNACION_PLATAFORMA AP
    LEFT JOIN PLATAFORMA P ON AP.PLATAFORMA_PLAT_ID = P.PLAT_ID
    WHERE AP.FECHA_ASIGNACION BETWEEN '2023-11-01' AND '2023-11-30'
    AND P.NOMBRE = 'RED GPS';

